name: minimal_onboarding
description: Flutter package for a quick minimal onboarding page
version: 0.0.1
homepage: https://github.com/alihussam/minimal_onboarding

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
