name: minimal_onboarding
description: A Flutter package to create a quick and minimal onboarding screen with multiple pages each with a description, title and picture.
version: 1.0.0
homepage: https://github.com/alihussam/minimal_onboarding

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
